set HOME=C:\PAW
rem set EDITOR=c:\dos\edit
set EDITOR=c:\me\me1
set KUIPPAGER=c:\me\me1
set GRXFONT=%HOME%\libgrx\fonts
set D2MACRO=%HOME%\D2MACRO

REM set PSVIEWER=c:\gs\outps386
REM set HOST_PRINTER=c:\gs\outps386

REM set GO32=driver %HOME%\LIBGRX\tr8900.grn gw 1024 gh 768 nc 256
REM set DEFAULT_FONT=cour20b
rem set DEFAULT_FONT=XM10X20b

rem Some puzzle (topline):
rem set GO32=topline driver %HOME%\LIBGRX\tr8900.grn gw 1024 gh 768 nc 256

REM rem set GO32=gw 800 gh 600 nc 256 tw 80 th 43

    rem set GO32=driver %HOME%\LIBGRX\tr8900.grn gw 640 gh 480 nc 256
    rem set DEFAULT_FONT=pc8x14

rem --- without UNIVBE, else - red text background --- 
rem set GO32=gw 800 gh 600 nc 256
rem     -------------------------


rem set DEFAULT_FONT=PC8X14
rem set GO32=gw 640 gh 480 nc 16

rem -------------- Favorite settings -------------------
set GO32=driver %HOME%\LIBGRX\tr8900.grn gw 800 gh 600 nc 256
rem set DEFAULT_FONT=cour16b
set DEFAULT_FONT=pc8x14
rem set DEFAULT_FONT=pc8x16

set shell=c:\dos\vc

:end
