      REAL FUNCTION SLOPE1(XDUMMY)
*********************************************************
*                                                       *
* This file was generated by HUWFUN.                    *
*                                                       *
*********************************************************
*
*     N-tuple Id:     1    
*     N-tuple Title:  Sloped mirror. Rcol2,dhcol= 12. 60. f=140. cm
*     Creation:       23/09/98 15.41.55
*
*********************************************************
*
      COMMON /PAWIDN/ IDNEVT,VIDN1,VIDN2,VIDN3,VIDN(10)
*
*--   Ntuple Variable Declarations
*
      REAL part(6),ray0(6),raymir(6),raytst(6),raypmt(6),Rbox,Dbox,f
     + ,Rref,Rpmt,Rcol2,dhcol
      INTEGER ireg,ip,npart,intref
*
      COMMON /PAWCR4/ ireg,ip,npart,part,ray0,raymir,raytst,intref
     + ,raypmt,Rbox,Dbox,f,Rref,Rpmt,Rcol2,dhcol
*

*
*--   Enter user code here
*
      print*, 'At start IDNEVT=', IDNEVT

      id = 1
      print*, 'Look at OPTIC'
      ievent = 2
      call HGNTB(id,'OPTIC',ievent,ier)
*      IDNEVT = ievent
      if (ier.NE.0) then
         print*, 'Error reading OPTIC' 
      else
         print*, 'ip,ireg,npart:'
         print*, ip,ireg,npart
         print*, 'raymir:'
         print*, raymir
      endif

      print*, 'Look at PARAM'
      print*, 'Let assign e.g. Rbox=12345. and read Rbox from Ntuple'
      Rbox = 12345.
      print*, 'Rbox after assigning', Rbox
      print*, 'Read Ntuple now'
      ievent = 1
      call HGNTB(id,'PARAM',ievent,ier)
*      IDNEVT = ievent
      if (ier.NE.0) then
         print*, 'Error reading PARAM' 
      else
         print*, 'Rbox, Dbox, f, Rref, Rpmt, Rcol2, dhcol:'
         print*, Rbox, Dbox, f, Rref, Rpmt, Rcol2, dhcol
      endif

      print*, 'IDNEVT=', IDNEVT
      SLOPE1 = 1.
*
      END

